/**
 * 创建一个侧边栏允许你：
 - 创建一个有序的文档组
 - 为该组的每一个文档渲染一个侧边栏
 - 提供下一步/上一步的导航

 侧边栏可以从文件系统生成，或者在这里显式地定义。

 根据需要创建尽可能多的侧边栏。
 */

// @ts-check  // 开启 TypeScript 的类型检查功能

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 * 定义侧边栏的配置类型
 */
const sidebars = {
  // 默认情况下，Docusaurus 从 docs 文件夹结构中生成一个侧边栏
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}]

  // 但你也可以手动创建一个侧边栏
  /*
  tutorialSidebar: [
    'intro',  // 文档名称
    'hello',  // 文档名称
    {
      type: 'category',  // 类型为分类
      label: 'Tutorial',  // 该分类的标签名
      items: ['tutorial-basics/create-a-document'],  // 该分类下的文档列表
    },
  ],
   */
}

module.exports = sidebars  // 导出侧边栏的配置
