/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Resource
  resourceSidebar: [
    {
      type: "autogenerated",
      dirName: "Resource",
    },
  ],

  // Backend
  goSidebar: [
    {
      type: "autogenerated",
      dirName: "Backend/Go",
    },
  ],
  pythonSidebar: [
    {
      type: "autogenerated",
      dirName: "Backend/Python",
    },
  ],
  javaSidebar: [
    {
      type: "autogenerated",
      dirName: "Backend/Java",
    },
  ],
  dockerSidebar: [
    {
      type: "autogenerated",
      dirName: "Backend/Docker",
    },
  ],
  mysqlSidebar: [
    {
      type: "autogenerated",
      dirName: "Backend/MySQL",
    },
  ],
  redisSidebar: [
    {
      type: "autogenerated",
      dirName: "Backend/Redis",
    },
  ],
  nginxSidebar: [
    {
      type: "autogenerated",
      dirName: "Backend/Nginx",
    },
  ],
  elasticsearchSidebar: [
    {
      type: "autogenerated",
      dirName: "Backend/ElasticSearch",
    },
  ],
  mqSidebar: [
    {
      type: "autogenerated",
      dirName: "Backend/MQ",
    },
  ],
  mongodbSidebar: [
    {
      type: "autogenerated",
      dirName: "Backend/MongoDB",
    },
  ],
  gitSidebar: [
    {
      type: "autogenerated",
      dirName: "Backend/Git",
    },
  ],
  regularSidebar: [
    {
      type: "autogenerated",
      dirName: "Backend/Regular",
    },
  ],

  // Frontend
  javascriptSidebar: [
    {
      type: "autogenerated",
      dirName: "Frontend/JavaScript",
    },
  ],
  typescriptSidebar: [
    {
      type: "autogenerated",
      dirName: "Frontend/TypeScript",
    },
  ],
  vueSidebar: [
    {
      type: "autogenerated",
      dirName: "Frontend/Vue",
    },
  ],
  reactSidebar: [
    {
      type: "autogenerated",
      dirName: "Frontend/React",
    },
  ],
  htmlSidebar: [
    {
      type: "autogenerated",
      dirName: "Frontend/HTML",
    },
  ],
  cssSidebar: [
    {
      type: "autogenerated",
      dirName: "Frontend/CSS",
    },
  ],
  domSidebar: [
    {
      type: "autogenerated",
      dirName: "Frontend/DOM",
    },
  ],
  bomSidebar: [
    {
      type: "autogenerated",
      dirName: "Frontend/BOM",
    },
  ],
  nodeSidebar: [
    {
      type: "autogenerated",
      dirName: "Frontend/Node",
    },
  ],
  electronSidebar: [
    {
      type: "autogenerated",
      dirName: "Frontend/Electron",
    },
  ],
  engineeringSidebar: [
    {
      type: "autogenerated",
      dirName: "Frontend/Engineering",
    },
  ],
  quasarSidebar: [
    {
      type: "autogenerated",
      dirName: "Frontend/Quasar",
    },
  ],

  // Interview
  interviewBackendSidebar: [
    {
      type: "autogenerated",
      dirName: "Interview/Backend",
    },
  ],
  interviewFrontendSidebar: [
    {
      type: "autogenerated",
      dirName: "Interview/Frontend",
    },
  ],


  // Network
  networkAjaxSidebar: [
    {
      type: "autogenerated",
      dirName: "Network/AJAX",
    },
  ],
  networkHttpSidebar: [
    {
      type: "autogenerated",
      dirName: "Network/HTTP",
    },
  ],

  // Web3
  web3IpfsSidebar: [
    {
      type: "autogenerated",
      dirName: "Web3/IPFS",
    },
  ],

  web3LearningSidebar: [
    {
      type: "autogenerated",
      dirName: "Web3/Learning",
    },
  ],

  // Resource
  resourceSoftSidebar: [
    {
      type: "autogenerated",
      dirName: "Resource/Soft",
    },
  ],

  // Other
  otherCookbookSidebar: [
    {
      type: "autogenerated",
      dirName: "Other/CookBook",
    },
  ],
  otherNotesSidebar: [
    {
      type: "autogenerated",
      dirName: "Other/Notes",
    },
  ],
}

module.exports = sidebars
